### ISSUE TITLE
Unexpected exception when sending Close frame.

### ISSUE THREAD

**Issue by damsfx** [ilyasozkurt/automobile-models-and-specs#6]
Running the `php artisan scrape:automobiles` command end with an error : 
```bash
 php artisan scrape:automobiles

 Do you want to start over? (yes/no):
 > no

 [INFO] Looking for brands.

 124/124 [============================] 100%
 [INFO] 124 brands inserted/updated on database.

 [INFO] Looking for automobile models.

   Wrench\Exception\FrameException

  Unexpected exception when sending Close frame.

  at P:\_Sites\_Labs\automobile-models-and-specs\scrapper\vendor\chrome-php\wrench\src\Client.php:264
    260▕         $payload = $this->protocol->getClosePayload($reason);
    261▕
    262▕         if ($this->socket) {
    263▕             if (!$payload->sendToSocket($this->socket)) {
  ➜ 264▕                 throw new FrameException('Unexpected exception when sending Close frame.');
    265▕             }
    266▕             // The client SHOULD wait for the server to close the connection
    267▕             $this->socket->receive();
    268▕             $this->socket->disconnect();

  1   P:\_Sites\_Labs\automobile-models-and-specs\scrapper\vendor\chrome-php\chrome\src\Communication\Socket\Wrench.php:128
      Wrench\Client::disconnect()

  2   P:\_Sites\_Labs\automobile-models-and-specs\scrapper\vendor\chrome-php\chrome\src\Communication\Connection.php:196
      HeadlessChromium\Communication\Socket\Wrench::disconnect()
```
The corresponding `laravel.log` file : 
```
[2024-10-28 14:18:03] local.ERROR: Unexpected exception when sending Close frame. {"exception":"[object] (Wrench\\Exception\\FrameException(code: 0): Unexpected exception when sending Close frame. at P:\\_Sites\\_Labs\\automobile-models-and-specs\\scrapper\\vendor\\chrome-php\\wrench\\src\\Client.php:264)
[stacktrace]
#0 P:\\_Sites\\_Labs\\automobile-models-and-specs\\scrapper\\vendor\\chrome-php\\chrome\\src\\Communication\\Socket\\Wrench.php(128): Wrench\\Client->disconnect(1000)
#1 P:\\_Sites\\_Labs\\automobile-models-and-specs\\scrapper\\vendor\\chrome-php\\chrome\\src\\Communication\\Connection.php(196): HeadlessChromium\\Communication\\Socket\\Wrench->disconnect()
#2 P:\\_Sites\\_Labs\\automobile-models-and-specs\\scrapper\\vendor\\chrome-php\\chrome\\src\\Browser\\BrowserProcess.php(225): HeadlessChromium\\Communication\\Connection->disconnect()
#3 P:\\_Sites\\_Labs\\automobile-models-and-specs\\scrapper\\vendor\\chrome-php\\chrome\\src\\Browser\\ProcessAwareBrowser.php(36): HeadlessChromium\\Browser\\BrowserProcess->kill()
#4 P:\\_Sites\\_Labs\\automobile-models-and-specs\\scrapper\\app\\Helpers\\Browser.php(58): HeadlessChromium\\Browser\\ProcessAwareBrowser->close()
#5 P:\\_Sites\\_Labs\\automobile-models-and-specs\\scrapper\\app\\Helpers\\Browser.php(86): destroyBrowser()
#6 P:\\_Sites\\_Labs\\automobile-models-and-specs\\scrapper\\app\\Helpers\\Browser.php(210): renewBrowser()
#7 P:\\_Sites\\_Labs\\automobile-models-and-specs\\scrapper\\app\\Console\\Commands\\ScrapeAutomobiles.php(261): browseUrlPost('https://www.aut...', Array)
#8 P:\\_Sites\\_Labs\\automobile-models-and-specs\\scrapper\\app\\Console\\Commands\\ScrapeAutomobiles.php(69): App\\Console\\Commands\\ScrapeAutomobiles->getAutomobileRowDOMs()
```

**Comment by ilyasozkurt** [comment]
Hola,

Please use pre scraped data if you need data quickly. I'm going to check this case.

**Comment by damsfx** [comment]
@ilyasozkurt No news on this??

On further investigation, I realize that I have a timeout on this function call:
https://github.com/ilyasozkurt/automobile-models-and-specs/blob/980b351ec7031fc0cdb840e348482ebf85df73e3/scrapper/app/Helpers/Browser.php#L203

Then when trying to renew the browser the error occurs.
